### ISSUE TITLE
Can't disconnect Github Action CD

### ISSUE THREAD

**Issue by NoelOConnell** [microsoft/azure-container-apps#101]
I setup continuous deployment for Azure Container Apps via the Azure Portal.

I edited and renamed the generated yml file and used it as a starting point.
I now have my deployment working via a custom GH Action.

The problem is both my GH Action and the Continuous Deployment are both running so I can see 2 revisions created a few minutes apart.

I've tried to disconnect the Continuous Deployment from the Azure Portal and I get a success message but it never actually disconnects.
I also tried to delete the action via the CLI command `az containerapp github-action delete` and it returns the following generic message.
`Command group 'containerapp github-action' is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus`

**Severity**
Annoyance - creates 2 revisions on PR merge.

**Comment by kendallroden** [comment]
Hey Noel. We are making changes to the implementation and the UI. You probably had trouble here because you renamed the action, then when you tried to delete it, so the portal couldn't find your action. This confusion should be resolved. Also, you can always change the trigger type to prevent the action from running, or delete it directly from your repo. In general, taking this feedback and will ensure we consider this scenario.
