### ISSUE TITLE
Container App Jobs - Seeking clarification on difference between parallelism and max execution count 

### ISSUE THREAD

**Issue by evanjamesjackson** [microsoft/azure-container-apps#1052]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [ ] bug report -> please search issues before submitting
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
I have a job that processes items from a Redis queue. I have the job scaled to start when there is at least one item in the queue (and, currently, I have `Max executions` set to `1`). The actual code in the job spawns a child process that reads and processes all items in the queue. Once that child process is done, the job exits. 

I would like this job to run in a parallel fashion (my code is already engineered to deal with concurrency), but I'm confused about whether to use the `parallelism` setting, or to increase the `Max executions` count. I tested a bit and found that increasing the `parallelism` setting spawns more "replicas" within a single execution, while increasing `Max executions` obviously spawns the set number of executions. In my use case, is there any difference between the two settings, or is one preferred over the other? What is the functional difference between a "replica" and an "execution", at least in this use case?

This may be less an issue and moreso a misunderstanding on my part (or a place where documentation could be a little clearer).

**Comment by anandanthony** [comment]
@evanjamesjackson if you want to run the job to start multiple execution replicas parallel to each other then you can set the `parallelism` setting to more than 1. I hope the following structure helps:

- S1: Parallelism 1, Completion: 1
  Container App Job resource --> execution --> replica_e1

- S2 (a): if lets say if we set the `parallelism` to 2, and completion to 2 then the above scenario would be:
  Container App Job resource --> execution --> replica_e1_1
                                                                       --> replica_e1_2
- S2 (b): parallelism: 3, completion: 2
  Container App Job resource --> execution --> replica_e1_1
                                                                       --> replica_e1_2
(Note: in scenario S2(b), even though parallelism is 3, only 2 replicas are created since the job mentions that it requires only 2 replicas to complete for the job to be successful)

The `maxExecution` property is specific to Event triggered jobs, which determines that for each polling interval how many individual executions can be created. So, let's take the above scenario(S2) and suppose that the maxExecution value was 2 and you had 3 messages in the queue, there would just be 2 individual executions that would start during the given polling interval and would process 2 messages in the queue.

For your scenario, if you expect the job to create multiple execution in a given interval to process different messages in the queue, you can increase the maxExecution count.
