### ISSUE TITLE
Event Driven Azure ContainerApps Jobs doesn't scale as expected with Azure Storage Queue

### ISSUE THREAD

**Issue by kgaurav1023** [microsoft/azure-container-apps#1107]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
A clear and concise description of the observed issue.
I have a Azure Container App Job Which fetch a single message from Azure Storage Queue, delete the queue message. and process them. the message processing takes around 15 mins. When I push 5 messages to the Storage Queue it creates 5 jobs and they works perfectly. However while the 5 jobs are still running if I send 1 more message to queue it doesn't start a new job 6th in the next polling till the previous jobs gets completed.
One can use sample from https://learn.microsoft.com/en-us/azure/container-apps/jobs?tabs=azure-cli#event-driven-jobs

### Steps to reproduce
1. .. Create a Event Driven Jobs which connects to Azure Storage Queue.
2.  Push Multiple messages to create a multiple Jobs. in jobs just put some wait so that they doesn't gets completed.
3.  While the jobs are still running push new messages to Queue.
4.  it will not start a new job till the current set of jobs gets completed.

**Expected behavior** [What you expected to happen.]
While existing jobs are still running, new jobs should be started when new messages gets arrived.

**Actual behavior** [What actually happened.]
Once jobs gets started for 1 Pooling period, it doesn't start new job executions till the running jobs gets completed. Once the running jobs get completed than it starts new job and only create 1 job even though there are multiple messages are pending in queue.

**Screenshots**         
I was doing some search and found that the video https://techcommunity.microsoft.com/t5/apps-on-azure-blog/azure-container-apps-newsletter-september-2023/ba-p/3943676 has a valid question from Deepesh Bathija at 37:10.

![image](https://github.com/microsoft/azure-container-apps/assets/55825239/19483d68-5c13-4b86-a198-643912ae100c)

### Additional context
Ex. Did this issue occur in the CLI or the Portal?

**Comment by anthonychu** [comment]
@kgaurav1023 can you try deleting the message after you finish processing? 

The scaler reads the message count of the queue as part of its calculations of how many job executions to start.

In your example, in the first polling interval, it will see 5 messages in the queue and calculate how many executions to start:

```math
queueLength - runningExecutions = executionsToStart
```

Which is 

```math
5 - 0 = 5
```

However, because the job executions delete the messages immediately, when you add another message, the scaler only sees 1 message at the next polling interval, and 5 executions have already been started

```math
1 - 5 = -4
```

So it won’t start any more executions until the existing ones are complete. 

Because your job executions run for 15 minutes, you’ll also need to ensure the message it’s processing is hidden from other jobs until it’s complete by configuring the visibility timeout.

**Comment by kgaurav1023** [comment]
Hello @anthonychu It worked the you have described.
