### ISSUE TITLE
ACA jobs with KEDA to scale self-hosted Github runners for whole org

### ISSUE THREAD

**Issue by jgresc** [microsoft/azure-container-apps#1133]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [ ] bug report -> please search issues before submitting
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
I followed the [tutorial from MSFT](https://learn.microsoft.com/en-us/azure/container-apps/tutorial-ci-cd-runners-jobs?tabs=bash&pivots=container-apps-jobs-self-hosted-ci-cd-github-actions) to setup ACA jobs for self-hosted Github Runners scaling with KEDA.
However, I don't want to specificly have the KEDA scaler only watching specific repositories, but rather have all repositories in my org scanned by it. According to the [KEDA](https://keda.sh/docs/2.13/scalers/github-runner/) documentation, the repos meta-data parameter is optional. When I pass the repos in this parameter, ACA jobs are picked up automatically from Github. When I leave it out, nothing happens. I don't get any error message.

```
az containerapp job create -n "aca-job" -g rg --environment aca-env \
    --trigger-type "Event" \
    --replica-timeout 1800 \
    --replica-retry-limit 1 \
    --replica-completion-count 1 \
    --parallelism 1 \
    --image "myacr.azurecr.io/my-runner:1.0.0" \
    --min-executions 0 \
    --max-executions 10 \
    --polling-interval 10 \
     --scale-rule-name "github-runner-my-org" \
     --scale-rule-type "github-runner" \
     --scale-rule-metadata \
         "owner=my-org" \
         "runnerScope=org" \
         "labels=my-label" \
         "applicationID=******" \
         "installationID=******" \
     --scale-rule-auth "appKey=pem-file" \
    --cpu "2.0" \
    --memory "4Gi" \
    --registry-server "myacr.azurecr.io" \
    --registry-username "acrusername" \
    --registry-password "acrsecret" \
    --secrets "pem-file=$pem"\
    --env-vars  \
         "GITHUB_APP_PEM_FILE=$pem" \
         "GITHUB_APP_ID=******" \
         "GITHUB_APP_INSTALLATION_ID=*******" \
         "CONFIG_URL=https://github.com/my-org" \
         "REGISTRATION_TOKEN_API_URL=https://api.github.com/orgs/my-org/actions/runners/registration-token" \
         "LABELS=my-label" \
```

**Expected behavior** [What you expected to happen.]
Start ACA job for any Github workflow in the org

**Actual behavior** [What actually happened.]
No ACA job started

**Comment by anandanthony** [comment]
@jgresc the [documentation](https://learn.microsoft.com/en-us/azure/container-apps/tutorial-ci-cd-runners-jobs?tabs=bash&pivots=container-apps-jobs-self-hosted-ci-cd-github-actions) has the steps to configure a `github-runner` scaler with source as repo.

In case you need to configure your ACA Job's `github-runner` scaler to work for scope - org, then there are few additional changes that need to be done:
-  The `REGISTRATION_TOKEN_API_URL` is set to org based URL like - `https://api.github.com/orgs/<orgName>/actions/runners/registration-token` (I see you have done this). This is based on the example given in GitHub's [documentation](https://docs.github.com/en/rest/actions/self-hosted-runners?apiVersion=2022-11-28#create-a-registration-token-for-an-organization)
- `REPO_URL` is also updated to the respective Org specific URL - `https://github.com/orgName`. This is since the container expects the URL to generate the token, refer [entrypoint.sh](https://github.com/Azure-Samples/container-apps-ci-cd-runner-tutorial/blob/d9175f4c0fe094736677640f0867dc88f0ccfc3d/github-actions-runner/entrypoint.sh#L11C20-L11C28), which should be similar to the config.sh command given in the GitHub documentation.
- The PAT token should have org specific permissions. For my tests, I used a token with the following permission and the owner being the org that I wanted the scaler to target:
![image](https://github.com/microsoft/azure-container-apps/assets/29655676/89d1dfc4-83ad-41c2-aaef-b8b2a6260dac)

After making these changes, I was able to get the ACA Job to pick up workflows queued across different repos in my org.

**Comment by jgresc** [comment]
> @jgresc the [documentation](https://learn.microsoft.com/en-us/azure/container-apps/tutorial-ci-cd-runners-jobs?tabs=bash&pivots=container-apps-jobs-self-hosted-ci-cd-github-actions) has the steps to configure a `github-runner` scaler with source as repo.
> 
> In case you need to configure your ACA Job's `github-runner` scaler to work for scope - org, then there are few additional changes that need to be done:
> 
> * The `REGISTRATION_TOKEN_API_URL` is set to org based URL like - `https://api.github.com/orgs/<orgName>/actions/runners/registration-token` (I see you have done this). This is based on the example given in GitHub's [documentation](https://docs.github.com/en/rest/actions/self-hosted-runners?apiVersion=2022-11-28#create-a-registration-token-for-an-organization)
> * `REPO_URL` is also updated to the respective Org specific URL - `https://github.com/orgName`. This is since the container expects the URL to generate the token, refer [entrypoint.sh](https://github.com/Azure-Samples/container-apps-ci-cd-runner-tutorial/blob/d9175f4c0fe094736677640f0867dc88f0ccfc3d/github-actions-runner/entrypoint.sh#L11C20-L11C28), which should be similar to the config.sh command given in the GitHub documentation.
> * The PAT token should have org specific permissions. For my tests, I used a token with the following permission and the owner being the org that I wanted the scaler to target:
>   ![image](https://private-user-images.githubusercontent.com/29655676/320190921-89d1dfc4-83ad-41c2-aaef-b8b2a6260dac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1NTM3NjcsIm5iZiI6MTcxMjU1MzQ2NywicGF0aCI6Ii8yOTY1NTY3Ni8zMjAxOTA5MjEtODlkMWRmYzQtODNhZC00MWMyLWFhZWYtYjhiMmE2MjYwZGFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA4VDA1MTc0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJhMmYyMmIwMTg4NjVhMGViOGUxZDg2OWViYzM2NjI4N2I5ZWZkNmQyZGI4ZDQ1ZjY0MDg3YzJmOTcyNzM3NDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DFBuRZ2PCA_j3gRhCycfdKtPyBChNnddqebSD-uuO50)
> 
> After making these changes, we were able to get the ACA Job to pick up workflows queued across different repos in my org.

Hi @anandanthony 
Thanks for your reply. 

-  `REGISTRATION_TOKEN_API_URL` is configured
- `REPO_URL` / `ORG_URL` is also configured, I pass it in the `CONFIG_URL` to the entrypoint.sh
- I don't use a personal access token, I am using the Github Apps PEM/PK for authentication. That's why I pass the `appKey` parameter to KEDA.

**Comment by anandanthony** [comment]
@jgresc wanted to check if you have tried authenticating with a PAT token? I am not sure if GitHub APIs in question can use PEM key for authentication. This [documentation](https://docs.github.com/en/rest/actions/self-hosted-runners?apiVersion=2022-11-28#create-a-registration-token-for-an-organization) just has information on how to use access tokens.

Also, the image's entrypoint[https://github.com/Azure-Samples/container-apps-ci-cd-runner-tutorial/blob/main/github-actions-runner/entrypoint.sh] in the documentation uses the PAT token to generate the registration token.

**Comment by anandanthony** [comment]
@jgresc can you please share your ACA Job name and subscription with us at [acasupport@microsoft.com](acasupport@microsoft.com) and we can further investigate this.

**Comment by devopstesting101** [comment]
Hi there!

I can confirm that `GitHub App installation access token` definitely works with an `org` scope for KEDA-scaled apps job self-hosted runners. 

Hopefully you have already got this working since the last comment, but just wanted to share this `Azure CLI` guide [here](https://github.com/ethorneloe/azure-apps-jobs-github-runners) with steps for both `repo` and `org` scoped runners.

There is also a `bicep` based guide [here](https://github.com/xmi-cs/aca-gh-actions-runner)

Hope this helps!

**Comment by ethorneloe** [comment]
Hi there!

I can confirm that `GitHub App installation access token` definitely works with an `org` scope for KEDA-scaled apps job self-hosted runners. 

Hopefully you have already got this working since the last comment, but just wanted to share this `Azure CLI` guide [here](https://github.com/ethorneloe/azure-apps-jobs-github-runners) with steps for both `repo` and `org` scoped runners.

There is also a `bicep` based guide [here](https://github.com/xmi-cs/aca-gh-actions-runner)

Hope this helps!
