### ISSUE TITLE
Secrets: referencing a non-versioned Key Vault secret automatically becomes a "Contaner App Secret" and does not remain a reference

### ISSUE THREAD

**Issue by DmitriyAlergant-T1A** [microsoft/azure-container-apps#1140]
### This issue is a: (mark with an x)
- [X ] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
In my Azure Container App, I need to create secrets based on a Key Vault. I have set up Managed Identity. When I reference a versioned secret (ex: https://my-....kv.vault.azure.net/secrets/openai-api-key/abce1234abcd1234dfgd765), it works as documented - the secret value keeps showing the KV URL. 

When I reference a NON-VERSIONED secret, latest version: https://my-....kv.vault.azure.net/secrets/openai-api-key it also works, but apparently the app ingests the copy of the secret value and it becomes a "Container Apps Secret" (with the value that was  automatically copied from Key Vault) - which is contrary to the documentation and to common sense.

### Steps to reproduce
1. Create a new Azure Container App using Azure Portal
2. Enable System-Assigned Managed Identity, and grant IAM role (Secrets User) on the Key Vault to the App's Managed Identity
3. In "Secrets" tab, Add a secret as a "Key Vault reference" and provide a versinoined secret URL  and Managed Identity: System-Assigned. Save the secret. Acknowledge the revision redeployment if needed.
4.  Press the "(eye) Click to show value" button -> see the actual secret value [not an expected behavior]
5. Click "Edit" on the secret. It will show its type being "Container Apps Secret" [not an expected behavior, and not what was selected during secret creation]

**Expected behavior**

A non-versioned KV-based secret remains a KV reference and does not somehow become a Container Apps Secret 

**Actual behavior**

- A non-versioned KV-based secret automatically become a Container Apps Secret - a bug
- A versioned KV-based secret remains a reference as expected

**Screenshots**         

Sorry, not applicable - the problem needs to be observed in dynamic, can't prove with a screenshot.
But it appears to be readily reproducable. I've reproduced it several times consistently.

### Additional context
Ex. Did this issue occur in the CLI or the Portal?

**Comment by vturecek** [comment]
@DmitriyAlergant-T1A - Prior to API version 2024-02-02-preview, the "list secrets" Container Apps API would show the secret _value_ for a KeyVault reference (in the same sense that the secret value is available to the code running in the Container App). It does not mean the Key Vault secret was converted to an inline Container Apps Secret. The portal UX uses the "list secrets" API to render the list of secrest for a Container App, and it appears as an inline secret when an older API version is used because the value is returned by the API.

You can always check this by using the "JSON View" link in the top right of the "Overview" page in the portal. This will show you the actual Container App definition, which is the source of truth. You can verify here that the secret is in fact referencing Key Vault. 

In API version 2024-02-02-preview, we no longer return the secret value for KeyVault references, and in the portal UX it will show the KeyVault URL for the secret instead.
