### ISSUE TITLE
Can not remove container app

### ISSUE THREAD

**Issue by nguyenson66** [microsoft/azure-container-apps#1246]
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

**Comment by simonjj** [comment]
Thank you for reaching out @nguyenson66. This is very likely related to a VNet update I see being performed just before 6am UTC. Please open a support case to get this resolved if you need more help. Once you find out exactly what the issue was could you please update this issue here as well to help others.

**Comment by nguyenson66** [comment]
> Thank you for reaching out @nguyenson66. This is very likely related to a VNet update I see being performed just before 6am UTC. Please open a support case to get this resolved if you need more help. Once you find out exactly what the issue was could you please update this issue here as well to help others.

Thanks @simonjj i found the issue report: https://github.com/microsoft/azure-container-apps/issues/1196, i got the same error, which has been going on since june 12, but it still not resolved
