### ISSUE TITLE
Feature Request: Reserved Instances for Workload Profile Environments

### ISSUE THREAD

**Issue by ractando** [microsoft/azure-container-apps#1286]
**Is your feature request related to a problem? Please describe**.  
As described here (https://learn.microsoft.com/en-us/azure/cost-management-billing/reservations/prepare-buy-reservation) Azure has a feature of Reserved Instances that help save costs by committing to one-year or three-years plans. We want the same feature to be extended to Azure Container Apps (Dedicated Workload Profiles).

**Describe the solution you'd like**.    
Workload Profiles should have an option of reserving number of instances for a particular profile.

**Describe alternatives you've considered**.   
None

**Additional context**.  
NA

**Comment by ractando** [comment]
Anyone to acknowledge this ?

**Comment by simonjj** [comment]
@ractando thank you reaching out. We currently have no plans to add the ability for reserved instances to Container Apps (ACA) workload profiles. ACA does offer a savings plan as of last year, so this may be something of interest? https://azure.microsoft.com/en-us/updates/generally-available-azure-container-apps-savings-plan-support/ 

Will this work for you?

**Comment by swissbuechi** [comment]
Hi @simonjj,

Savings plans help, but the ceiling is low. ACA gives you 15% on a 1-year commitment and 17% on 3 years. Reserved Instances on the underlying VM SKUs go up to 72% for 3 years.

The practical result is that AKS is still cheaper for steady-state workloads, purely because node pools can use RIs and ACA workload profiles can't. In cost comparisons this keeps pushing workloads towards AKS, even where the simpler ACA setup would be the better fit.

Dedicated workload profiles already run on fixed instances that stay provisioned regardless of app scaling, so a reservation model seems like a reasonable fit. Either proper RI support, or a much better savings plan rate specifically for dedicated profile environments, would close the gap.

Is there anything you can share on whether this is being looked at?

**Comment by richard-sistern** [comment]
App Service supports reservations on the premium tier, there would seem to be no good reason for ACA not to.
