### ISSUE TITLE
Azure CLI Reference

### ISSUE THREAD

**Issue by dotnetron** [microsoft/azure-container-apps#131]
Hello,

I realize this service is in preview, so docs may not be completely built out as yet, but where can I find the complete azure cli reference for the extension? Specifically, I am trying to create a container app pointing to an image in Azure Container Registry (ACR) and trying to understand how to specify the authentication credentials to ACR. The docs [here](https://docs.microsoft.com/en-us/azure/container-apps/get-started-existing-container-image?tabs=bash&pivots=container-apps-private-registry) reference --registry-username and --registry-password, however the intellisense in VS Code does not pick those up. It shows a --service-principal parameter which ideally is what I would like to use.

Also, I tried using the username and password parameters and it looks like the deployment was successful and app was created, but when i go to the **Continuous Deployment**  tab of the app on the Azure Portal, it doesnt show the correct image (looks like it is using the application name) and the container does not appear to start or be working when I browse to the URL. How would I go about troubleshooting this?

Thanks,
Param

**Comment by dotnetron** [comment]
To further add, when i go to **Revision Management** on the Azure Portal, I see 1 entry in there with a provision state of failed. How could I determine where the issue is now?

**Comment by kendallroden** [comment]
Hi @dotnetron. A few things: 

We don't have a full CLI reference currently, we are in the middle of making significant CLI changes and improvements, so you can expect CLI documentation to be released soon. In the meantime running `az containerapp create -h` will provide you with a list of sample CLI commands that can help you accomplish your objective. 

We do not have any built in VS Code support at this time, so that is likely your issue regarding intellisense. We are working on a VS Code extension. We also don't support service principal auth to a container registry today. 

In terms of Continuous Deployment, you have to set that up after your initial container app deployment. It does not auto-create on your behalf after the initial deployment. When you set it up, it will auto-generate an image name for you instead of using the name of the image that is currently running. I believe we were going to update this behavior; I will talk to the team and check with them. I imagine you have not actually enabled continuous deployment - if you did it would generate a GitHub action for you which you can edit and modify locally to generate the name of the image you want to build and any tags you want to add yourself.

If your container app is not running after the initial deployment, I recommend first checking log analytics. This is where you will see any logs that your container outputs to standard out/error. You can navigate to the log analytics workspace and run a query similar to the one here: 
"ContainerAppConsoleLogs_CL | where ContainerAppName_s == 'yourappname' | project ContainerAppName_s, Log_s, TimeGenerated | order by asc" 
We are working on log streaming where you will be able to do this more easily. 

Let me know if you need any other assistance

**Comment by dotnetron** [comment]
Hi Kendall,

Thanks for getting back to me. I did review the help docs on `az container app create -h` and noticed a few things:

- I did not see a way to create an environment. The portal experience allows me to specify things like using my own VNet and Log Analytics workspace etc. Would be great to see that added to the cli at some point.
- The --registry-username and --registry-password - should those be the admin user account for the container registry? Or can it be an Azure AD user account which has access Pull to ACR?

I am not following you on setting up Continuous Deployment and GH actions? We have a private code repo on Azure DevOps and we are pushing images to Azure Container Registry through Azure pipelines. Will those not auto-trigger a new deployment in the Container App? 

I was able to review the log analytics after the initial deployment. It turned out to be a startup exception for our .net web api app. Log streaming would be a fantastic addition (assuming it would work similar to how it does in App Service?).

**Comment by dotnetron** [comment]
Also, I noticed that when creating the app via the portal and selecting the internal only option for ingress, it still created public ip addresses and a **kubernetes** and **kubernetes-internal** load balancers. Are both necessary if we only want to expose our apps internally? We plan on putting an Application Gateway in front of them to expose them to the outside world.

**Comment by dotnetron** [comment]
For the registry username/password, is there a way to pass in either `System.Management.Automation.PSCredential` or even a SecureString? Same goes for setting the secrets. Can we use SecureString for certain secrets?

**Comment by kendallroden** [comment]
@dotnetron sorry for missing your continued asks. Let me know these are still relevant :)

**Comment by BigMorty** [comment]
Complete CLI reference can be found here - https://docs.microsoft.com/en-us/cli/azure/containerapp?view=azure-cli-latest&preserve-view=true
