### ISSUE TITLE
Feature Request: Deploy Logic Apps Standard to Azure Container Apps

### ISSUE THREAD

**Issue by scleynen** [microsoft/azure-container-apps#173]
With Logic Apps Standard it is possible to run your Logic Apps as a container and run it anywhere. When you run it on AKS with Azure Arc you get the same experience in the portal and for deploying as when using them within an App Service Plan.

I'd like to have the extra option to deploy the Logic App container to an Azure Container App iso an AKS with Azure ARC. You could see it as enabling Azure ARC on the Azure Container Apps. That way it would be possible to have kind of best of 2 worlds. Logic Apps can run in a "serverless" way inside a container on a Container App and you get the same (developer) experience and you don't nee to manage and setup an AKS yourself and could use KEDA, DAPR,....

**Comment by LianaAdaza** [comment]
Thank you for your request. I'm happy to inform that Azure Container Apps on Azure Arc has been in public preview since December 2022. Furthermore, Logic Apps has released a hybrid deployment model, where users can deploy Standard logic app workflows hosted on premises as part of an Azure Container Apps extension. We hope these address your interest. Thank you again.

Resources: 
https://learn.microsoft.com/en-us/azure/container-apps/azure-arc-overview
https://learn.microsoft.com/en-us/azure/logic-apps/set-up-standard-workflows-hybrid-deployment-requirements
