### ISSUE TITLE
Feature Request: use managed identity for ACR pull

### ISSUE THREAD

**Issue by anthonychu** [microsoft/azure-container-apps#183]
**Is your feature request related to a problem? Please describe**.  
https://github.com/microsoft/azure-container-apps/issues/16#issuecomment-1017511067 @inuvano-labs

**Describe alternatives you've considered**.   
Currently only supports username and password.

**Comment by kendallroden** [comment]
@anthonychu can we close?

**Comment by alexv-be** [comment]
To the best of my knowledge this is not supported.
Managed identities work on the container level, not sufficient for pulling from an ACR. Unless I'm misreading something & testing things in the wrong way.

**Comment by xaviervv** [comment]
I noticed that az cli (containerapp extension) does have an option to use system assigned under the repo settings
az containerapp registry set --identity system

Help docs: 
"The managed identity with which to authenticate to the Azure Container Registry (instead of username/password). Use 'system' for a system-defined identity or a resource id for a user-defined identity. The managed identity should have been assigned acrpull permissions on the ACR before deployment (use 'az role assignment create --role acrpull ...')."

I still need to test if it actually work, and if can be set in arm templates as well.

**Comment by alexdrenea** [comment]
can confirm this works with AZ CLI
- Enable system-assigned identity at the container app level
- assign acrpull role to identity 
- authenticate container to ACR using "system" option instead of user

Some open questions
- Will this work with user-assigned identities?
- Can it be achieved in ARM?

**Comment by cwe1ss** [comment]
I have been using it with user-assigned identities and Bicep templates for the last two weeks - no issues so far!

**Comment by onionhammer** [comment]
Weird this issue is open if it works? Did microsoft forget about it?

**Comment by kendallroden** [comment]
This feature exists today- closing to avoid confusion regarding the feature itself. If you have issues using it, or have doc suggestions please open an issue for those respective topics! Thanks
