### ISSUE TITLE
Delay traffic routing changes until Readiness probe

### ISSUE THREAD

**Issue by jeffhollan** [microsoft/azure-container-apps#184]
Would be nice if when making a change to traffic routing (or when making a change to `latest`) if the traffic rules didn't shift until the destination containers were "ready" to match traffic and scale.  Maybe this is opt in, but the feature in mind is:

Simple Scenario:
I have 1 container revision with a simple traffic rule of 100% to latest. It is running on one replica. I send a constant ping of traffic to it. I deploy an update that creates a new revision, and that instance implements readiness checks. Container Apps waits until the new revision is responding to the readiness successfully before shifting 100% of traffic to it (that way I don't see any disruption in my constant pings)

More advanced scenario - maybe pieces of this are opt-in (maybe these should be two seperate issues? Dunno):
I have a container app that has multiple revisions that are active (like a 50/30/20 split). The 50 split is currently service requests across 10 replicas for scale. I signal intent to update the traffic rule destination for the "50" split to a new revision (currently running on zero replicas).  Ideally I'd see no "disruption" in throughput, which may mean that not only would we need to wait for readiness probes to show green, we may need to even pre-scale to 10 replicas that have readiness green. That way once traffic shifts and now 50% of traffic goes to the new revision, there is no disruption in throughput / latency. Potentially this could happen gradually (1 replica at a time) as they come online.

**Comment by michaelmcneilnet** [comment]
This would be a great addition! We currently fall into a variation of the simple scenario. We want revision A at 100% traffic, create a new revision B, have all of the replicas in revision B report ready, and then revision B receives 100% of the traffic.

We've currently implemented this using Multiple Revision mode and a custom powershell script, as we found that single revision mode killed revision A on creation of revision B, leaving us no time to wait for B to be ready before transferring the traffic. There is also the limitation that because our powershell script is external, the best we can do is hit the load balancer for the revision and check that at least one of the replicas is returning as ready. If this was supported natively by ACA then **all** replicas could be probed and the traffic shifted when all replicas are ready.

**Comment by KaiWalter** [comment]
@dariagrigoriu this would actually play well into our Service Fabric container migration scenario.
CC: @TorstenH82 @fl-lutz @SteveeeP

**Comment by ezYakaEagle442** [comment]
I have a customer having also this requirement.
@jeffhollan , how does it work today when deploying a new revision, is it a K8S rolling update which means 100% of the traffic is redirected to the new revision wether it is up & running or not ?

**Comment by onionhammer** [comment]
I didn't realize that this wasnt the case by default .. during preview. What's the point of a readiness probe if this sample case isn't covered?

**Comment by onionhammer** [comment]
This appears to be working now.

**Comment by ahmelsayed** [comment]
Yes, I'll close this as complete. There are more details in this comment about how this works. https://github.com/microsoft/azure-container-apps/issues/244#issuecomment-1309085556
