### ISSUE TITLE
Feature Request: Container Apps with multiple ports to expose outside of the environment

### ISSUE THREAD

**Issue by vimorra** [microsoft/azure-container-apps#201]
**Is your feature request related to a problem? Please describe**.  
With the current implementation ACA is limited to applications that expose only one port externally to the environment because the ingress, actually can be configured only to route into one target port.
https://docs.microsoft.com/en-us/azure/container-apps/ingress?tabs=bash

**Describe the solution you'd like**.    
The desired solution is to have an ingress that can be configured to expose multiple ports and not only 80 or 443. Another alternative solution can be to use ingress rules based on path, in order to route the traffic to a dedicated target port.
Regarding the first approach a possible solution can be to this one
![image](https://user-images.githubusercontent.com/48756634/165757733-46f33398-fcee-4b5d-b004-085b707f6799.png)

In this way when the ingress is configured is required to add a new param in the API to manage the port to expose and how to map this with the targetPort.
The traffic rules to split traffic between revisions can be the same as is it is now, but usually TCP connection are not linked to services/apps that can have mutiple revisions at the time, like databases or mining pool.

**Additional context**.  
The problem was discovered during an assessment to host Ethereum mining pool

**Comment by cbellee** [comment]
I'm trying to configue ACA to use Dapr event grid input bindings, but due to the restriction of only being able to expose a single port via the ingress controller, this doesn't seem to be possible. The event grid input binding component requires an additional [handshake port](https://docs.dapr.io/reference/components-reference/supported-bindings/eventgrid/) to be exposed in order to validate the webhook.

**Comment by msatyan** [comment]
My solution has two ports, we would like to have facility to access both the ports

**Comment by AlexQBox** [comment]
Hoping this can be implemented to get [Selenium Grid](https://github.com/SeleniumHQ/docker-selenium) running.

**Comment by dariagrigoriu** [comment]
This is not part of the Azure Container Apps roadmap at this time.

**Comment by xtianus79** [comment]
@vimorra Is there anyway to use a container app or any Azure container service that will expose outside ports to the ones I want?

**Comment by xtianus79** [comment]
@dariagrigoriu this is a pretty severe limitation on Azure Container Apps. Why would this not be on the roadmap?

**Comment by dneogi** [comment]
I have two ports exposed in my docker file: 8080 and 9000
I have HTTP listening on port 8080 and gRPC on 9000.
Using Azure Container Instance, I can get my docker image to work correctly.
However, using Azure Container App, I am unable to expose both the ports. I tried both TCP but that still allows exposing one port. Am I missing something or is this a limitation of Azure Container Apps?

**Comment by Kris-Turk** [comment]
Is there any movement on this, I need to expose two ports (80 and 2525). Agree with the above this significantly limits ACA

**Comment by duglin** [comment]
Some background questions...
- does "multiple ports exposed on the app" mean that the client must see things as separate ports or, as someone suggested, could ACA map different paths to different ports on the app? Obvious, an HTTP only option, not TCP.
- if ACA can do this via path-based routing, could the app not do so as well (today)?
- does the app need to be able to mandate the non-80 port numbers used? Or could ACA only support, say, ports 80 though 90? same for SSL (443->453)

**Comment by markheath** [comment]
The scenario I was looking at was hosting maildev which exposes one port for HTTP and another for SMTP https://maildev.github.io/maildev/ (uses ports 1080 and 1025)
I ended up just using Azure Container Instances instead for it.

**Comment by Kris-Turk** [comment]
@markheath  I have very similar requirement as I was deploying SMTP4Dev - https://github.com/rnwood/smtp4dev and also ended up using container instances :)

**Comment by torosent** [comment]
Hi, It's not in the public roadmap but we are activity working on it.

**Comment by Expecho** [comment]
@torosent can we keep this issue open until the feature is GA or in preview so it is easer to keep track of this?

**Comment by Expecho** [comment]
@torosent Thanks for reopening the issue. Since it is not on the public roadmap but it is in active development can you share any (rough) estimated completion date?

**Comment by damianh** [comment]
Good to hear it's on roadmap.

To share my use case, I want to separate application traffic on one port from management/operational traffic on another port.

**Comment by karimch27** [comment]
nothing new on this ?

**Comment by cbellee** [comment]
The multiple port feature is now in preview.

https://learn.microsoft.com/en-us/azure/container-apps/ingress-overview#additional-tcp-ports

https://github.com/microsoft/azure-container-apps/issues/546

**Comment by DzianisMatveyeu** [comment]
when it will be available in the Azure portal and Terraform config?

**Comment by garrettsingletary** [comment]
Has anyone got this to work successfully yet? I am still only able to access over a single port. I am using the yaml config with additionalPortMappings defined but none of those ports are open for connections.

**Comment by dneogi** [comment]
I have this working:
https://learn.microsoft.com/en-us/azure/container-apps/ingress-how-to?pivots=azure-cli#use-additional-tcp-ports
Make sure you create a new Container App Environment with a custom VNET
--------------------------------
Start at the Azure portal home page
Search for Container Apps in the top search bar
Select Container Apps in the search results
Select the Create button.
Basics tab
Select your Azure subscription
Create a new resources group or reuse the one for the environment
Enter container app name: <container name>
Create an Environment tab
Select the appropriate region

In the Create Container Apps environment field, select the Create new link

In the Create Container Apps Environment page on the Basics tab, enter the following values:

Environment name: <your env name>

Zone redundancy: disabled

Select the Networking tab to create a VNET

Select Yes next to Use your own virtual network

Next to the Virtual network box, select the Create new link and enter the following value:

Name: <your-custom-vnet>

Select the OK button

Next to the Infrastructure subnet box, select the Create new link and enter the following values

Subnet Name: <your-custom-vnet>

Let the default values on the other fields

Select OK

Under Virtual IP, select External.

Select Create.
---------------------------------
Continue to deploy the ContainerApp and then follow the CLI command to deploy new containerapps in the container app environment. In order to create the container app you will have to run the following command and pass a yaml file as parameter:
az containerapp create --name <your-app-name> --resource-group <your-resource-group-name> --yaml <yaml-file-path>

**Comment by cachai2** [comment]
Hi folks, closing this issue as the feature has been [GA as of January, 2024](https://azure.microsoft.com/en-us/updates/generally-available-azure-container-apps-supports-additional-tcp-ports/). Please reach out to acasupport [at] microsoft [dot] com or open a new issue if you run into any bugs or the feature isn't working as expected.
