### ISSUE TITLE
Custom name for the MC_ resource group 

### ISSUE THREAD

**Issue by lgmorand** [microsoft/azure-container-apps#207]
By default, when using a existing VNet (not by default and I don't know why), a MC_ resource group is created. The name is random (twice the same generated string: MC_salmonsea-3086035e-rg_salmonsea-3086035e_westeurope) and it could cause an issue when naming policies are in place 

**Describe the solution you'd like**.    
A parameter to specify the RG name like we have with AKS (--node-resource-group)

It may be planned or available in CLI later on but I prefer to track it because it'd be showstopper for several of my customers.

**Comment by torosent** [comment]
Thanks @lgmorand . I added this item to our backlog.

**Comment by azureholic** [comment]
I have a customer who has policies that require the presence of certain tags on each resourcegroup. So in addition to a custom name for the MC-resourcegroup, could we also add custom tags to it during provisioning?

**Comment by ezYakaEagle442** [comment]
see also [https://github.com/microsoft/azure-container-apps/issues/345](https://github.com/microsoft/azure-container-apps/issues/345)

**Comment by raddaoui** [comment]
I have a customer that needs either to add tags to the managed resource group and/or decide what the name of the managed resource group will be because they have policies based on tagging and resource group names that prohibits the creation of resources like public IPs, Load Balancers that are deployed in the managed RG and currently providing a general exclusion for resource groups prefixed with “MC_” isn’t ideal.

**Comment by mthoger** [comment]
> I have a customer that needs either to add tags to the managed resource group and/or decide what the name of the managed resource group will be because they have policies based on tagging and resource group names that prohibits the creation of resources like public IPs, Load Balancers that are deployed in the managed RG and currently providing a general exclusion for resource groups prefixed with “MC_” isn’t ideal.

@raddaoui how do you go about, creating policy exclusion generally for prefixed resource groups ? 
I like to implement container apps environments and app using devops pipelines, however im not able to exclude policies befor I know the name of the MC_ resource groups

**Comment by anrub** [comment]
I would rather not see this resource group at all - especially the Public-IP although the capps env is VNet integrated. Our policies mostly block Public IPs, so we always need exemptions for this cases.

**Comment by SteWilson** [comment]
Hi, 

I believe this issue has been blocking me for the last few weeks also. I have been trying to create a container app with a new / existing vnet with it always failing with the error: "Managed environment failed to initialize due to cluster provision failed"

I (and Azure Support) were not able to find any more information to give us a clue as to what the issue really was. Support wanted to inspect the vnet I was creating so I kicked off another deployment today to find it complete successfully.

To cut the story short I realised that creating a container app environment using an existing vnet creates the mentioned MC_ resource group. The issue I was facing is that we have policies enforced by IT for the naming convention of resources and resource groups which these automatically generated resources do not comply with. 

I will raise this with our IT in the short term as I do not know if they intend to re-apply the policy but it would be very helpful to be able to control the naming of these resources (and as the comments above state, their tags).

**Comment by andrekiba** [comment]
@torosent why the resources that are inside the MC_ resource group cannot be created inside the resource group where everything else is?? What happens if I need to move the container app from one subscription to another one?

**Comment by stfnzl** [comment]
I'm joining the club here. I think the MC_ resource group should not be shown at all since consumers should not need mess with it. Alternatively offer the possibility to give it a user-defined name.

**Comment by devtrf** [comment]
I'll make the comments of everyone else here mine, too. Either allow it to be custom, or make it invisible to the user.

**Comment by onionhammer** [comment]
> I'll make the comments of everyone else here mine, too. Either allow it to be custom, or make it invisible to the user.

I think it's already in preview at least, it's available in ARM

**Comment by torosent** [comment]
This option is available in Workload Profiles - Consumption/Dedicated. It will not be available in `Consumption Only` mode
![image](https://github.com/microsoft/azure-container-apps/assets/17064840/4542b951-33fa-45e8-b82f-024b27347557)

**Comment by lgmorand** [comment]
@torosent Thanks for the update :) For our curiosity, why a differient behavior for consumption only mode, since it also create a RG with a non compliant name ? Can we expect it to disappear totally ?

**Comment by SteWilson** [comment]
> I'll make the comments of everyone else here mine, too. Either allow it to be custom, or make it invisible to the user.

I don't think we are in a place where it can be invisible/hidden as I believe you need access to the load balancer if you want to use a private link to the CAE. Hopefully use cases such as this will be matured in the future which may lead to not needing to access them directly but for the time being, the ability to rename the RG would be the way to go.

**Comment by cachai2** [comment]
Closing as customizing the resource group name is supported for workload profile environments: [Managed resource group for workload profiles environments](https://learn.microsoft.com/en-us/azure/container-apps/networking?tabs=workload-profiles-env%2Cazure-cli#workload-profiles-environment-2).  Please reopen if needed.

**Comment by lgmorand** [comment]
@cachai2 Hi Cary

could you at least please explain why we don't have the same behavior with consumption only ?
