### ISSUE TITLE
Dapr calls GET /dapr/config on Services

### ISSUE THREAD

**Issue by JohnFasc** [microsoft/azure-container-apps#294]
### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
Dapr calls GET /dapr/config on all my services. Is there a specific implementation that i miss? 
This behavior creates misleading telemetry in my app insights. 

### Steps to reproduct
1. .. Create an default service with application insights 
2. .. Publish and activate dapr

**Screenshots**         

![image](https://user-images.githubusercontent.com/73105921/177113879-a2d1ac35-8df3-4a7d-b3a9-658ff5ccf061.png)
![image](https://user-images.githubusercontent.com/73105921/177114183-960ad778-240e-40cb-bc43-bc13d4ff5502.png)

**Comment by kendallroden** [comment]
Hi @JohnFasc - in order to wire up certain settings dapr calls from sidecar to app for example, in the case of pubsub the /dapr/subscribe endpoint is hit on the app to determine which topics, if any, a dapr app should subscribe to. In the case of the /dapr/config endpoint, this retrieves the registered actors in Dapr. If you are not making use of dapr actors, this will return a 404. @berndverst if my understanding is correct this is expected behavior that would only be mitigated by not running the dapr placement pod?

**Comment by JohnFasc** [comment]
Hi @kendallroden, thank you for the response. I implemented an controller which returns an empty result for the dapr configuration. That solved my problem with the misleading errors.
