### ISSUE TITLE
Container app not updating

### ISSUE THREAD

**Issue by szavoda** [microsoft/azure-container-apps#311]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [ x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [x ] regression (a behavior that used to work and stopped in a new release)

### Issue description

After updating a docker image with "latest" tag and uploading to Azure Registry and issuing the az containerapp update command, the container app still has the previous image intact.  The CLI command reports success.

Additionally, if I attempt to create a new revision via the portal, it also reports success but never creates a new revision.

If you change the scale or modify the image directly in the portal

### Steps to reproduce

1. Create a new container app - can be based on Hello World
2. Add a new revision via portal
3. After notification of success, refresh to see same revision in place.

**Expected behavior** [What you expected to happen.]

New revision is created with latest image

**Actual behavior** [What actually happened.]

Old revision remains with old image

**Comment by anthonychu** [comment]
If you issue an update command without changing anything in the container app, a new revision is not created and the existing revision is not restarted. This means your changes to the `latest` tag is never picked up.

Please see this doc for recommended guidance on image tags: https://docs.microsoft.com/en-us/azure/container-registry/container-registry-image-tag-version

If you must use `latest`, you'll need to restart the Container Apps revision. You can do this with the CLI's `az containerapp revision restart` command.

**Comment by szavoda** [comment]
The doc reference is an excellent source.  Also, good info for the restart CLI command.  I think between these two, this feature request is no longer needed.

**Comment by paul-green** [comment]
Bit late to the party - but using the full digest instead of the image:tag format will work.

e.g. get the full digest of an image:tag
`
docker pull your-repo.com/your-image:your-tag
imageDigest=$(docker inspect --format='{{index .RepoDigests 0}}' your-repo.com/your-image:your-tag)
`
This will return the full digest - e.g.;

your-repo.com/your-image@sha256:2ec4649b59ec93f674c2c9ae6839e44b63b1373fcb4eb76aa618d75e4a887769

Use this as the 'image' value. Since the digest will have changed (unlike the tag) the Container App will be updated

**Comment by vkrebs-wktaa** [comment]
Basically, I would agree that `latest` is not a version. But for fast prototyping, this behavior is really annoying.

I added an env var that is changed on every deployment.
`az containerapp up --env-vars DEPLOY_TIME_IN_SECONDS_SINCE_EPOCH=$(date +%s)`

**Comment by johschmidt42** [comment]
Thank you @paul-green for this suggestion! The image tag that is shown in the Portal (for me) is just the tag, not the digest though.

**Comment by TLA020** [comment]
> I found another workaround:
> 
> you can use --revision-suffix option to set a new suffix for your new revision. Even if the image name remains the same, the container app will be updated and the new image will be pulled.
> 
> in the gitlab CI, for instance, you can use a unique job identifier for the suffix
> 
> `az containerapp update --name $NAME --resource-group $RG --image $IMAGE --revision-suffix j${CI_JOB_ID}`

same behavior, when using imagename:latest in the update statement, nothing happens.  no revision is made.

**Comment by alexrecuenco** [comment]
I am not sure why this is not recommended. If I wanted a full pipeline for deployment, I would be using AKS instead of container apps with some GitOps platform. 

Some of the ease of working with container apps is that, in theory, I can just choose a few options in the azure portal and everything just works? But if I need to start creating strategies to update image, binding variables to force restarting etc... at a certain point it just becomes more convenient to just use AKS.

Would it be possible to reconsider some kind of hook that you can hit to request a refresh? Or any other approach that is recommended. This works perfectly well for Azure Web Applications, without having to handle managed identities on my CICD platform.
