### ISSUE TITLE
Feature Request: dapr-pubsub configuration binding via Azure Managed Identities

### ISSUE THREAD

**Issue by k-krupka** [microsoft/azure-container-apps#315]
**Is your feature request related to a problem? Please describe**.  
We want to use Azure Service Bus via [pubsub dapr component](https://docs.dapr.io/reference/components-reference/supported-pubsub/setup-azure-servicebus/) over Managed Identities. As of today, the situation is not possible as only the connection string is an option. References:
1. https://docs.dapr.io/reference/components-reference/supported-pubsub/setup-azure-servicebus/#azure-active-directory-aad-authentication
2. https://docs.microsoft.com/en-us/azure/container-apps/managed-identity?tabs=arm%2Cdotnet#limitations

**Describe the solution you'd like**.    
Assuming:
1. you have a managed identity
2. you grant the proper RBAC grant in service bus for the managed identity ( doh :) )

Ideally, the following would be perfect:
1. you create a dapr component for service bus pubsub in Azure Environment
4. as dapr-metadata you provide the namespace name
5. optionally, as dapr-metadata you provide a client id (appId in AAD) of the managed identity (if you have more and we have more, 1 user-assigned for container app, 1 user assigned for service bus interaction - shared with multiple container apps)
6. then you deploy a container app which uses the above and it works.

**Describe alternatives you've considered**. 
Passing an example Service Bus connection string works like a charm. No issue here.

**Additional context**.  
When we tested this "kind-of" solution, we've got the error in Log Analytics, in ContainerAppConsoleLogs_CL table: 
```
time="2022-07-14T15:24:12.981104983Z" level=warning msg="error initializing pub sub pubsub.azure.servicebus/v1: MSI not available" app_id=autodeploy02 instance=autodeploy02--439-99d9854d4-rwjng scope=dapr.runtime type=log ver=1.7.3-msft-1
time="2022-07-14T15:24:17.982122772Z" level=fatal msg="process component triggers error: MSI not available" app_id=autodeploy02 instance=autodeploy02--439-99d9854d4-rwjng scope=dapr.runtime type=log ver=1.7.3-msft-1
```

**Comment by onionhammer** [comment]
Highly recommend creating a user-assigned identity; annoying you have to reference the client id everywhere, but it solves a 'chicken and egg'  issue when creating a new environment from scripts/bicep where your ACA app cant pull images from ACR because the system-assigned managed identity hasnt been created/assigned `AcrPull` yet.

**Comment by kendallroden** [comment]
Yeah I agree @onionhammer... I think it makes most sense to use user assigned at least for dapr specifically. @cwe1ss I too ran into the problem when I didn't include the azureClientID. I wasn't initially aware this was a requirement. Instead of creating a new component for every app, I would consider using a shared user assigned identity for apps that need similar access policies on certain resources. I will still go back and talk to the team to see if there is a way we can try to optimize this experience

**Comment by rvanmaanen** [comment]
It would be great if any of the following could be done :)

- An update to the docs so it is clear that azureClientId is required. For instance here it's explicitly listed as optional: https://docs.dapr.io/developing-applications/integrations/azure/authenticating-azure/
- Also make it clear that the identity that is configured for the Component should be the assigned to the App as well. Or what would be even better if the azureClientId would indeed be optional and that it picks a system assigned identity when it's available, or a user assigned identity if there is only one.

If the above isn't possible, it would be great if we could assign an identity to the entire Container App Environment, which could be set as a node identity (while having the App identity itself set as pod identity). That way we could fix multiple problems: 
- We can create an identity (user or system assigned) and assign that one AcrPull rights so there is no chicken/egg problem anymore if we would want to use system assigned identities for Apps, because all nodes can pull from the Acr.
- This identity could maybe also be used for Dapr components (if so configured), so we can create a single CAE with a bunch of Dapr components that just have the proper rights. Teams could then just deploy their Apps and use the Components without having to know which identities to assign to their app.

Another option to let apps just have a single identity is to create Dapr components per app, but that feels wrong to me. I don't want to have to create app specific things in an environment that is shared over multiple apps. It would also cause the amount of components to explode, not sure if there is a limit.
