### ISSUE TITLE
Server gets unexpected EOF and client "Connection reset by peer" for requests with "big" body

### ISSUE THREAD

**Issue by quality-leftovers** [microsoft/azure-container-apps#351]
### This issue is a
- [x] bug report (possibly, not sure)
- [ ] documentation issue or request
- [ ] regression

### Issue description
I've deployed tusd file upload daemon (https://github.com/tus/tusd, image: registry.hub.docker.com/tusproject/tusd:sha-160e4d7) in an azure container app environment. The daemon receives chunked file uploads and stores them in an azure blob storage.

To do some testing I've also set up a JMeter script that acts as upload client and am running it using Azure load testing.

For some chunks being uploaded I get the following error:
- The client reports: Non HTTP response code: java.net.SocketException,Non HTTP response message: Connection reset by peer
- The server (container app) reports: event="BodyReadError" id="5363767c8d0c17d2306af71a6ef740c4" error="unexpected EOF"

I'm not sure this is a bug, my problem right now is that I have no idea how to find out what the underlying issue is.

### Steps to reproduct
1. Deploy tusd in azure container app
2.  Deploy upload clients (10 engines, each with 4 threads uploading 4 files each with 400 MiB using 10 MiB chunks)

(can provide JMeter script and container app definition)

**Expected behavior**
Connections are not forcefully closed

**Actual behavior**
```
Server receives unexpected EOF.
   event="BodyReadError" id="5363767c8d0c17d2306af71a6ef740c4" error="unexpected EOF" 
Client receives connection reset by peer.

Server tries to respond:
   event="ResponseOutgoing" status="500" method="PATCH" path="5363767c8d0c17d2306af71a6ef740c4" error="unexpected EOF" requestId="054efc6d-0a24-427c-9c4e-3d1fb06171d0"
```

### Additional context
- Test duration is shorter than azure container apps request timeout (240 secs)
- Resources
  - Replica count was set to min=max=20
  - CPU=2.0
- No errors im ContainerAppSystemLogs_CL
- Metrics
  - Replica restart count = 0
  - CPU max < 1.06 c
  - Memory max < 136.4 MiB
  - Network In max <= 10.1 GiB
  - Network out max <= 10.1 GiBGiB
  - Requests max <= 1.76 K
 - Concurrent API Clients: 40 in total (JMeter)
   - 10 engines (nodes)
   - 4 threads per node (clients)

**Comment by torosent** [comment]
@ahmelsayed, Can you help with this issue?

**Comment by ahmelsayed** [comment]
@quality-leftovers Is my understanding that this doesn't repro 100% but occasionally/intermittently correct?

Also based on your request path and load client (i.e: jmeter and `5363767c8d0c17d2306af71a6ef740c4`) can you reach out to me through ahmels@microsoft.com with your app and environment name? Since based on some logs I have some questions and don't want to expose more about that in a public forum unless you're also ok with that. Some logs that match the above description from around august 9th show that the client disconnected too early, which would be a client issue. But I want to verify it was actually your client, and not just another random client that matched on that ID.

Otherwise, I'd like to try to repro this if you can share the jmeter script.

**Comment by quality-leftovers** [comment]
It reproduces for each test suite run, I'll re-create my test setup and once I've done so reach out to you via a mail (most likely tomorrow)

**Comment by kendallroden** [comment]
Can we confirm if the above moved forward and there was a resolution? @quality-leftovers

**Comment by dale-personal** [comment]
This could be related to this issue:
https://github.com/microsoft/azure-container-apps/issues/116
