### ISSUE TITLE
Integrate Azure Front Door with Container Apps

### ISSUE THREAD

**Issue by Vinayak014** [microsoft/azure-container-apps#471]
I plan to use Azure Front Door in front of my Container App and allow access only through Front Door. I have deployed an Internal Container Apps environment with a custom virtual network. I have added an NSG to the infra-subnet with an Inbound Rule that allows Azure FrontDoor.Backend. But this doesn't seem to work. 

Any suggestions on how to use Azure Front Door with Azure Container Apps?

**Comment by o-l-a-v** [comment]
We'll be looking at combining Front Door with Application Gateway so the requests to ACA originates from within a VNet. This example template shows how that can be setup so that Application Gateway only accepts one given Front Door:

* https://azure.microsoft.com/en-ca/resources/templates/front-door-standard-premium-application-gateway-public/

The tag "FrontDoor.Backend" will accept traffic from any Front Door in azure, not just yours. Just download this list of service tags mapped to IP addresses and see for yourselves:

* https://www.microsoft.com/en-us/download/details.aspx?id=56519

If you still want to go Front Door only, you should somehow validate the headers identifying your exact Azure Front Door instance, described here:

* https://learn.microsoft.com/en-us/azure/frontdoor/origin-security

Another future option, hopefully: Azure Front door has private link to backend resources in preview, but currently does only support a few resource types as backend. See:

* https://learn.microsoft.com/en-us/azure/frontdoor/private-link#limitations

**Comment by kendallroden** [comment]
We have this item tracked in our documentation backlog and are working on content around this integration

**Comment by kendallroden** [comment]
I am closing this, not because its not important but because we have another item on this https://github.com/microsoft/azure-container-apps/issues/402
