### ISSUE TITLE
Unable to pull image from ACR

### ISSUE THREAD

**Issue by famda** [microsoft/azure-container-apps#50]
Hi,
I'm trying to automate a pipeline to deploy container apps using a private ACR repo. I'm not being able to pass from authentication to pull the image.

I followed this:
https://t.co/cUqLnVTOwx

It creates everything except the last command because of permissions to pull the image.
"Error details: Code: 90712, ExtendedCode: 90712, Message: Error pulling the container image. Please check the image name or any registry credentials to access if required.."

This script it's being executed in a release pipeline in azure devops.

Are you able to help?

**Comment by famda** [comment]
Hey,
The issue is related with the service principle permissions.
Enabling the admin user on ACR and passing as parameter on create command works.

Maybe updating the samples with the azure cli commands to create the service principal and adding those to create and update commands would be nice.

What do you think?

Using this admin user is something that makes me unconfortable.

**Comment by mikeball** [comment]
I have this working using a service principal in the AcrPull role. In the update command you will need to specify the registry, the user and the password. If your registry name is too long you will need to use yaml file. Also the `-secrets` isn't working/used at the moment because of some bug. I have also seen this same error happen with valid creds, it sometimes fails, but then worked on retry. See https://github.com/microsoft/azure-container-apps/issues/41

**Comment by frbar** [comment]
Thanks @famda - for others (like me) struggling with the same issue, this is how you can pass the admin user, while waiting for a better solution/fix:

```
az containerapp create `
  --name XXX `
  --resource-group XXX `
  --environment XXX `
  --image XXX.azurecr.io/XXX:latest `
  --registry-login-server XXX.azurecr.io `
  --registry-username XXX`
  --registry-password XXX
```

**Comment by mikeball** [comment]
This may be related. https://github.com/microsoft/azure-container-apps/issues/10#issuecomment-967430684
