### ISSUE TITLE
Provisioning a new AC environment with App fails with conflict with a custom VNET

### ISSUE THREAD

**Issue by ceramey1997** [microsoft/azure-container-apps#518]
Please provide us with the following information:
This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
## Issue description
Provisioning to a custom /18 Vnet fails into a new resource group East US2
Zone redundancy disabled.
Use Internal LoadBalancer.

{ "status": "Failed", "error": { "code": "OperationFailed", "message": "Managed environment failed to initialize" } }

Correlation ID: 72bbd464-2c84-41ff-b535-9856c25c5277
Service Request ID: 70922559-eb8c-47e9-a918-058573620ac4

Steps to reproduct
All actions via Portal.

Create VNET with a /18 Subnet
Create Container Apps environment with new Resource Group (Location EastUS2), new Analytics Log Space,
Create an App with the default quickstartet app.
Expected behavior [What you expected to happen.]
ACA environment is provsioned correctly and app is deployed.

Actual behavior [What actually happened.]
Log Analytics workspace is created, but during provisioning of ACA the process fails with conflict.
{ "status": "Failed", "error": { "code": "OperationFailed", "message": "Managed environment failed to initialize" } }

**Comment by kendallroden** [comment]
@ceramey1997 Sorry you are running into this. Likely there are errors in the provisioning process that are not propagating as expected. In order to best support, can you please open a support ticket with the appropriate information if this is still occurring. If you are unable to do so, can you send your information, including subscription and environment name to [acasupport@microsoft.com](mailto:acasupport@microsoft.com)

**Comment by simonjj** [comment]
We've addressed several issues around this. I don't think this exists anymore. Closing for now, if this still happens please reopen and point to this issue.
