### ISSUE TITLE
507 responses with "exceeded request buffer limit while retrying upstream"

### ISSUE THREAD

**Issue by jsuchome** [microsoft/azure-container-apps#519]
### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description

We have several (4) applications deployed as Container Apps, all sharing same Environment. Since Dec 1st, we started to experience 507 return codes with "exceeded request buffer limit while retrying upstream"

We are not aware of any significant change on our side, the traffic is generally the same.

AFAICS the error is coming from istio, so my assumption is that it's some new configuration being deployed on ACA side.

At one point I thought that the problem might come from the fact that our applications are sharing the Environment. So I created new Environments so I have a situation with 1-1 mapping for some (not all) applications. However the error is still there, even for those application that have unique environment.

**Expected behavior** [What you expected to happen.]

No 507 errors getting from my services.

**Actual behavior** [What actually happened.]

From time to time (like 1 in 100 requests, but that's not exact measure), we get 507 that we weren't used to get before Dec 1.

**Comment by ahmelsayed** [comment]
Just to update on this. @jsuchome I'm assuming you're using the [auto authentication](https://learn.microsoft.com/en-us/azure/container-apps/authentication) feature, right? There was a race condition introduced between when the application is ready vs when the auth service is ready. The sometimes the app gets ready before the auth service, and this causes the first couple of requests on activation (or scale out) to maybe reach an auth service that's not yet ready. This should be fixed in the next release.

**Comment by jsuchome** [comment]
@ahmelsayed , thanks for response! Yes, we're using authentication set up from Container Apps dashboard.

So you're saying this is happening during the scale out, when I am contacting the new replica(s)? 

When can we expect new release?

**Comment by ahmelsayed** [comment]
this should be deployed now.

**Comment by Fariz-fx** [comment]
On aug 2023 at 9 20 pm UTC and aug 31 2023 on 12 29 am ist received this error code in our container app which runs fastapi 

Kindly analyse this issue and avoid it in future
