### ISSUE TITLE
Support Subnet Size /27

### ISSUE THREAD

**Issue by SophCarp** [microsoft/azure-container-apps#584]
8/30 2023 GA Announcement: https://aka.ms/container-apps-udr 

Docs: https://aka.ms/container-apps-udr

Note: With workload profiles environment, the minimum subnet size required is a /27 CIDR. A minimum subnet size of /23 is still required for container apps created on the consumption only environment type.

**Comment by rhuanbarreto** [comment]
How can we have access to this? Just adding a 27 subnet works?

**Comment by creyesprog** [comment]
Noticed this has moved to public preview but it still isn't working:
![image](https://user-images.githubusercontent.com/40253026/229840955-d219dc7f-7077-4fcf-ae71-a16bbbf8e3e2.png)

Do we need to update something in Azure in order to utilize this new version?

**Comment by cachai2** [comment]
Hi @creyesprog and @rhuanbarreto, smaller subnet sizes are in preview with the new [Consumption + Dedicated plan structure](https://learn.microsoft.com/en-us/azure/container-apps/plans#consumption--dedicated-plan-structure-preview). For more details on the networking capabilities of the new Consumption + Dedicated plan structure, see [here](https://learn.microsoft.com/en-us/azure/container-apps/networking#architecture-selection). For steps on how to create Container Apps on this plan, see [here](https://learn.microsoft.com/en-us/azure/container-apps/workload-profiles-manage-cli?tabs=external-env). 

If you can try this and let us know if you are still running into issues or if it's working, that would be great. We'd love to hear your feedback!

**Comment by hbalaci** [comment]
ACA is been great in proof of concept so far ! 

Still, I have few questions:
 * When more regions will be added to the preview for [Consumption + Dedicated plan structure](https://learn.microsoft.com/en-us/azure/container-apps/plans#consumption--dedicated-plan-structure-preview)? Canada Central, Canada East?
* What is a rough estimation for GA for workload profiles?
* Is there any plan to support hardware profiles that have GPU support?

**Comment by dav1dli** [comment]
I don't need any dedicated profiles. I need to conserve IPs. The following scenario works:
* create ACA environment with a minimal dedicated, get Consumption + Dedicated available on the environment, get the friendly info that dedicated will cost $244/month
* Use /27 subnet as part of the env config
* Consumption plan is attached nevertheless and it is the default to which apps are deployed in not chosen otherwise.
* Remove the Dedicated configuration
The ACA environment is still there, custom subnet is there, apps can be deployed and appear to function correctly. Overall the configuration appears to be functional.

Questions:
* why not to enable smaller subnets on the default Consumption plan straight away?
* how this environment will be billed?
