### ISSUE TITLE
Key vault Support for Secret Management

### ISSUE THREAD

**Issue by SophCarp** [microsoft/azure-container-apps#608]
ETA: Public Preview by end of March 2023

**Comment by SophCarp** [comment]
Related to issue #7

**Comment by GurliGebis** [comment]
We are in april now, is there an ETA on the preview? (not to sound impatient or trying to rush, I'm just curious)

**Comment by tamland** [comment]
Seems like this was just added? https://github.com/Azure/azure-cli-extensions/blob/main/src/containerapp/HISTORY.rst#0327

**Comment by onionhammer** [comment]
Oooh, exciting... is there docs? Can I use it with bicep as well?

**Comment by anthonychu** [comment]
Yes, this feature should be in preview very soon and we'll have docs.

If you want to try this today, here's the tl;dr:

* Use API version `2022-11-01-preview`
* In `secrets`, instead of specifying a `value`, specify 2 properties:
    * `keyVaultUrl`: URL to the secret in Key Vault. Can be versioned or non-versioned. If no version, Container Apps will poll Key Vault periodically; it'll update secret values and restart affected revisions automatically.
    * `identity`: The identity (full resource ID or `System`) used to retrieve value from Key Vault. Must have been granted proper access to the key vault.

```json
"resources": [
{
    ...
    "properties": {
        "configuration": {
            "secrets": [
            {
                "name": "queue-connection-string",
                "keyVaultUrl": "<KEY-VAULT-SECRET-URI>",
                "identity": "System"
            }],
        }
    }
}
```

There's a limitation today: you may need to first create the app and enable managed identity, then update the app to use Key Vault references.

**Comment by onionhammer** [comment]
@anthonychu does the limitation apply if your user assigned identity is created prior to the apps creation?
