### ISSUE TITLE
Secrets are stored as clear text.

### ISSUE THREAD

**Issue by ChendrayanV** [microsoft/azure-container-apps#64]
Secrets in Azure Container Apps are stored as clear text.  
Below image illustrates the secrets under container apps (deployed through devops) - I have to provide the docker credentials -  

```PowerShell
 secrets: [
        {
          name: 'container-registry-password'
          value: dockerRegistryPassword
        }
      ]
```

![image](https://user-images.githubusercontent.com/13730675/146715557-52b41661-5803-4fe4-88b7-2c30617ca1ea.png)

Here is the proof secrets in dapr (state store - azure table storage)
I deployed a container apps with azure table storage as a statestore. I observed the storage account key is stored as clear text. 
![image](https://user-images.githubusercontent.com/13730675/146715382-226756e5-9738-4230-af73-30f51fe5d643.png)

[containerapps.bicep](https://about-powershell.visualstudio.com/_git/iContoso?path=/modules/container-apps/containerapps.bicep)

**Comment by kendallroden** [comment]
Hi @ChendrayanV! I took a look at your bicep. It looks like you did not create a secret for the accountKey value. Instead of using the accountKey environment variable directly, you should add this value as a secret in the secret config section and reference it when creating the Dapr component. If you have any further questions on this please let me know. Otherwise I will close the issue if you are able to test!

**Comment by kendallroden** [comment]
@ChendrayanV will close this issue as it has been resolved. If you need any additional support don't hesitate to reach out!
