### ISSUE TITLE
Misleading pricing information re: load balancers and "scale to zero"

### ISSUE THREAD

**Issue by cemerick** [microsoft/azure-container-apps#657]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [ ] bug report -> please search issues before submitting
- [X] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description

ACA's [pricing page](https://azure.microsoft.com/en-us/pricing/details/container-apps/#pricing) reads (in part):

> Applications scale on-demand based on requests and events. Container Apps replicas are billed for active usage when they are running. An application can be configured to scale to zero replicas when there are no requests or events to process. No usage charges apply when an application is scaled to zero.

But this is simply not true: even when an app is "scaled to zero", usage charges accrue due to the environment's automatically-provisioned load balancer and any corresponding public IP addresses. These requirements are not mentioned anywhere on the pricing pages or other resources in the top-line marketing materials; AFAICT, the _only_ mention of the scale-invariant networking infra costs is pretty deep in the ACA documentation @ https://learn.microsoft.com/en-us/azure/container-apps/networking#managed-resources (corresponding to page 80 in the corresponding 400-page PDF version of the docs, just to give a sense of the needle-in-a-haystack nature of it).

This omission re: mandatory network infra costs is also repeated in the FAQ:

> Q: Does Container Apps support scale to zero pricing?
>
> A: Yes. You can scale to zero and only pay for when your app is active in response to events and/or requests.

Finally, the Azure pricing calculator shows no indication that there are mandatory network infra charges associated with ACA usage, even at "free"-tier levels of usage (i.e. below the 2-million-request mark that the calculator does note).

----

I understand that all of the scale-to-zero language is aiming to refer strictly to the actual container apps resources, but that's just not the whole story. To be clear, while I'm not concerned about costs associated with load balancers and public IPs, it would have been nice to know about them from the start; I don't think the current presentation of ACA costs/pricing tells the entire story in the right places, and I can imagine that others might find that dishonest. I understand not wanting to muddy the waters about container apps' value prop, but even just a footnote about the requisite minimal costs on the pricing page and in the calculator would IMO be the right thing to do; at least in the name of clarity & transparency, but also so that no one is surprised when e.g. load balancer charges start rolling in.

**Comment by SophCarp** [comment]
Thank you for sharing! The team appreciates your concerns, and we're discussing the issue.

**Comment by BigMorty** [comment]
I added the following note high up in the [billing help article](https://learn.microsoft.com/en-us/azure/container-apps/billing#consumption-plan). I have also asked a note to be added to the pricing page and calculator.
![image](https://user-images.githubusercontent.com/947510/229980493-646e809b-2df1-4a7e-b35e-6f789d415987.png)

**Comment by SophCarp** [comment]
As we've added this note, I want to confirm that we can close this issue. @cemerick does this address your concerns?

**Comment by cemerick** [comment]
Yup, presuming updates to the calculator / pricing page work their way in, this is fine.

**Comment by BigMorty** [comment]
@SophCarp, lets keep it open until I get confirmation of the changes to the pricing page and calculator. I have assigned it to me. Thanks!

**Comment by santo2** [comment]
thanks for adding the note... won't change the fact that we are now stuck with 300€ additional charges per month because of the choices we made

**Comment by andrey-roam** [comment]
same here, but when I chose to go with the default consumption plan (e.g. without my own vpc) , then I got into the issue of not having outbound internet access from the container running in the managed infrastructure

**Comment by decewei** [comment]
> same here, but when I chose to go with the default consumption plan (e.g. without my own vpc) , then I got into the issue of not having outbound internet access from the container running in the managed infrastructure

just fyi if you use workload profile, you can still have consumption; and you have outbound internet access. But I agree, the extra cost of bringing your own VNET is still not clear enough, and also almost does not make sense, especially when we can't configure the load balancer.

**Comment by craigshoemaker** [comment]
Closing this issue as the docs are now updated.

#please-close

**Comment by v-vish** [comment]
Closing this issue as the docs are now updated.

**Comment by a-matthew** [comment]
I understand that this issue was closed due to the update in the documentation, but I wouldn't say the update was sufficient at all.

Azure Portal seemingly does not point out additional costs from using Vnet in Container App Environment.
<img width="723" height="379" alt="Image" src="https://github.com/user-attachments/assets/03457de5-22cc-43b0-9a28-18e299fd4f3e" />

The official calculator only points out the term of "additional charges". In my case the Load Balancer that I 'don't need' costed around 10 times more than the Container App itself... (and I estimated it to be around 15$ at first, using the calculator, so the calculator was effectively of no use)

<img width="1091" height="78" alt="Image" src="https://github.com/user-attachments/assets/667219df-380f-404f-8802-1a3836d5451b" />

Looking into the documentation of LB for Container App Environment, the topic of Internal/External LB is not greatly documented. What is the price difference?

<img width="726" height="229" alt="Image" src="https://github.com/user-attachments/assets/390f294a-9eb9-4e1d-96ff-02632899a35b" />

ARM template documentation says: `"These environments do not have a public static IP resource. They must provide infrastructureSubnetId if enabling this property"`.

The whole point of Container Apps is to be able to scale vertically and horizontally. The benefit of supporting horizontal scaling is destroyed by 'premium' subnet integration, which is free with Container Groups/Instances...
