### ISSUE TITLE
Feature Request: can updating secrets be considered as 'revision-scoped changes' instead of 'application-scoped changes'?

### ISSUE THREAD

**Issue by hamenu** [microsoft/azure-container-apps#691]
**Is your feature request related to a problem? Please describe**.  
In [Application-scope changes](https://learn.microsoft.com/en-us/azure/container-apps/revisions#application-scope-changes) documentation, it's mentioned that updating a secret requires revisions to be restarted:

> [Secret values](https://learn.microsoft.com/en-us/azure/container-apps/manage-secrets) (revisions must be restarted before a container recognizes new secret values)

People use different tools for their infrastructure, as in Terraform, Pulumi, Bicep, or ARM and the source of the secrets can be anything (variables in the pipeline, variable groups in the project, key vault, etc.)

When deploying the infrastructure, regardless of the tool used, it's hard to find out if a secret was changed. Do we compare all secrets (10s of them) from existing container app with what's being inputted to the tool (ARM), then if changed, run `az containerapp revision restart`?

If infrastructure creates a new revision (by having revision-scoped changes as well as a secret change, i.e. application-scoped changes), hopefully, the new revision doesn't need a restart, right? If so, then we only need to check: _'if no new revision is created, and some secrets have changed (which is really hard by itself if not impossible), then and only then restart the running revisions'_

Because the above check is hard to perform, you end up creating a new revision every time you deploy the infrastructure, doing which could mean more changes to the pipeline, because if before no changes was made, no revision was created, no cold start, no outage, no risk, nothing. We are now forcing a deployment anyway.

**Describe the solution you'd like**.    
_'if a secret has changed'_ seems easy to detect for Azure (as you have done the same with non-secret environment variables and categorised them as revision-scoped changes). Why doesn't _Azure_ restart all revisions when secrets are changed? 🙂

Who wants to change a secret without wanting to see the change in their app anyway? 🤔

**Describe alternatives you've considered**.   
Since the check is hard to detect, we have to restart the revision anyway.

However, with single-revision container apps, because of the existing bugs below, it's possible that while restarting a new revision we could hit restarting the provision**ing** revision, and possibly receiving an error saying that the revision is not up or is transitioning or something 🤷
* https://github.com/microsoft/azure-container-apps/issues/598
* https://github.com/microsoft/azure-container-apps/issues/244

To avoid the possible _"revision is transitioning"_ or _"something-similar"_ error,  we have to wait until the new revision is provision**ed**, then restart it.

Why do you need to restart the new revision if it's being created, you ask? Well, going back to the _'hard to check if a secret has changed _and_ no revision-scoped change is in this run of infrastructure pipeline'_

You see how messy things are getting for just a simple restart? 😁

Can't you just re-categorise secret changes as 'revision-scoped' changes or force-restart the revisions? 🙂

**Additional context**.  
I don't think anything else is needed 🙂

**Comment by vturecek** [comment]
@hamenu The main reason we did it this way is to allow secret rotation to be automated without creating new revisions, which would be challenging to set up if you have multiple revisions with traffic shifting rules or custom revision names.

That said, having to restart a revision to consume new secret values is not ideal. The problem is that secrets are injected to your container as environment variables (which is also not ideal for other reasons). Would it help if you could mount secrets as files on disk (through a volume) instead, so that you can pick up changes programmatically without having to restart anything?

**Comment by hamenu** [comment]
Thanks @vturecek for your response.

We are using .NET Core (Web API and Function Apps), and all the settings are automatically mapped to `IConfiguration` when added as environment variables in container apps, whether as a `Manual entry` or `Reference a secret`. Mounting a file would mean custom code to load and map them to `IConfiguration`. Besides, some stuff like container registry password has to be a secret. Probably can't use volume mounts as a _complete_ replacement of secrets and we will eventually hit this problem again when changing a something-that-has-to-be-a-secret secret!

I guess restarting the revision every time we run the infrastructure pipeline would probably be an easier workaround.

However, would be good to know what happens when we run `az containerapp revision restart` command to decide where in the pipeline I should put it.

Does it go through downloading the image from container registry, passing the probes, etc. like the entire create-a-new-revision process, or does something simpler and less concerning happen in the background?

**Comment by vturecek** [comment]
Internally, `az containerapp revision restart` does a Kubernetes Deployment restart with a RollingUpdate strategy.

Just to be clear, what I was suggesting would be a new feature in Container Apps that would allow you to create a Secret as you do today, but instead of mapping it to an environment variable, it would be mapped to a file on disk that is projected into a volume in your container (cc @anthonychu).

`IConfiguration` has various providers for loading configuration from different places, environment variables being one of the defaults. If you have secrets on disk (depending on how we would mount them), the [Key per file configuration provider](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-7.0#key-per-file-configuration-provider) would probably work well. This might also save you the trouble of having to map all of your secrets to environment variables in your Container App spec as `secretrefs`. Let me know if that would work for you.

There are trade-offs to consider here:
 - Mounting secrets as files rather than environment variables is generally safer in terms of keeping your secrets from leaking. For instance, some logging libraries and debugging tools will dump process metadata that includes environment variables. Since secrets are plain text in environment variables, this could result in secrets getting logged and leaking. 
 - Using environment variables is generally safer in terms of deployments. With environment variables, you are forced to restart the process to consume new values. This has certain benefits:
   - Since the process restarts, you don't need to write error-prone hot-reloading config code (did you remember to clear old config values in all the places they might be cached or stored? Can you guarantee the new config value is used everywhere and you don't have any inconsistencies with in-flight or concurrent operations?)
   - Also since the process restarts, you can validate the new config values are correct on startup, and then use a rolling update deployment (like `az containerapp revision restart`) to carefully restart processes one upgrade domain at a time, run health checks, and make sure the new config value didn't break something. If the config value does break something causing your health probes to fail, the deployment is rolled back and your application continues to work.

**Comment by hamenu** [comment]
Technically speaking, yes; key-per-file configuration provider _could_ work but only in certain scenarios.

Can't speak for everyone, but I don't think key-per-file configuration is commonly used by .NET developers, especially when the default configuration supports all necessary use cases to run a .NET app on Azure App Service or Function App. So, even if the team spend the time and provides this option, it might not be widely used at the end and your time/effort would be in vain (although very much appreciated).

A scenario I can think of that this will not work is a queue-triggered function running as an Azure Function App that has a signature like this:
```
[FunctionName("QueueTrigger")]
public static void Run(
    [QueueTrigger("myqueue-items", Connection = "StorageConnectionAppSetting")] string myQueueItem)
{
    ....
}
```

It requires `StorageConnectionAppSetting` to be an app setting (which if I'm not mistaken means environment variables).

Even if I'm mistaken and I can trick Azure Functions runtime to pick up `StorageConnectionAppSetting` from a secret file, the problem is when this connection string changes: all the functions are registered _at startup_. So, in order for this change to take affect the app _has to_ restart and hot-loading does not help here (there are probably similar scenarios in nodejs or any other backend stack).

If I start treating these settings as secretRefs, some other settings as volume mounts, then I would eventually be back to the problem of _"it's hard to know what value changed and whether I need to restart the revision after a deployment or not._ I'll end up restarting it anyway.

Also, in Function Apps, no matter where you inject the key/values from into your settings, Azure Functions runtime, makes all of them accessible as environment variables (correct me if I'm wrong). So, it's not uncommon/wrong to see `Environment.GetEnvironmentVariable("<my-setting-that-came-from-keyvault-or-file-or-anything>")` in codebase.

So, even though key-per-file configuration provider could work in _some_ scenarios, I probably wouldn't be using it due to _"I'll end up restarting it anyway."_ explained above👆

> The main reason we did it this way is to allow secret rotation to be automated

I'm curious about this though; How can 'not' restarting a revision help that?

Secret rotation can be implemented in different ways depending on how the validator of that secret works, however a golden rule of secret rotation that works _everywhere_, is to have at least two secrets. The same way Azure has primary and secondary keys for Storage Accounts or Cosmos Accounts. You change the consumer to secret 'b' while you rotate secret 'a'.

If I have an API key from a third-party, and I want to rotate it, and it doesn't support two keys, very likely the moment I rotate the key, it's gonna reject the old API key. Doesn't matter if the secretRef in Container Apps changed, or whether or not the revision was restarted.

The third-party system doesn't care; you change the key, it's not valid anymore. Even if it's an Azure storage account and you are using primary key and you rotate it. Even if you don't restart the revision, the code using it is gonna fail.

I fail to see how it helps automate secret rotation if that was the main reason to not restart revisions automatically.

**Comment by vturecek** [comment]
@hamenu thanks for the candid feedback on storing secrets as volumes. I think there's still value in moving secrets out of environment variables for the reasons I mentioned earlier (they may get logged accidentally), but it sounds like restarting the revision after a deployment (assuming the deployment doesn't create a new revision) may be best for your scenario.

>I fail to see how it helps automate secret rotation if that was the main reason to not restart revisions automatically.

What I meant was that we made secrets "application-scoped" so that changing a secret value would not _create a new revision_, as that would then require you to also perform traffic shifting and revision management as part of your secret rotation, which we expected people would not want to happen (maybe our assumption was wrong there?).  

> hard to check if a secret has changed and no revision-scoped change is in this run of infrastructure pipeline

I can see how this would be difficult from a single deployment pipeline. Is it feasible to have a separate pipeline that is only used to update secrets and performs a revision restart?

**Comment by hamenu** [comment]
>  I think there's still value in moving secrets out of environment variables

Secrets as environment variables are not new to Container Apps and are in use in existing products:

* Azure Web App (in SCM you can see _all_ environment variables which includes all the configuration and connection strings)
* Azure Functions (even in code you use `Environment.GetEnvironmentVariable()`)
* Azure Pipelines, even secrets that are injected from a key vault, including Certificates, are available via environment variables; here is a message in pipeline variables UI: _"To use a secret variable in a script, you must explicitly map it as an environment variable."_
* Kubernetes itself: [Using Secrets as environment variables](https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets-as-environment-variables)

Secrets as file is not a silver bullet and safe either, unless you have encryption at rest, which then comes with the topic of Microsoft-managed key and customer-managed key.

Regardless, _"getting rid of environment variables for secrets"_ is a big enough topic to warrant its own GitHub issue.

As far as this issue is concerned, as you also agreed, unfortunately the problem can't be solved by volume mounts, so that's out of the window already.

> What I meant was that we made secrets "application-scoped" so that changing a secret value would not _create a new revision_, as that would then require you to also perform traffic shifting and revision management as part of your secret rotation

But, changing a secret does not require a _new_ revision and challenges with traffic shifting, you just need to _restart_ the revision.

Besides, _creating a revision_ with revision-scoped changes, and all the challenges of traffic shifting is already handled by the platform (container apps) itself, not users (developers/devops), isn't it? How does _restarting_ a revision when secrets change pose a different challenge? and what would that challenge be for? platform or developers/devops?

Maybe I still don't understand what you mean by _"secret rotation"_ 😕 Could you please make a concrete example if that's OK?

If there are other challenges/complexity associated with '_auto_ restart of revisions when secrets change' (or even if this is not a high priority in your backlog), I accept _"we cannot implement this right now"_ as an answer 🙂. I'm OK to implement some workaround even for months to come and just keep watching this issue to be resolved some day; but if it's just the "secret rotation" that stops the team from doing automated restarts, then would be good to understand that better.

**Comment by hamenu** [comment]
And as for the workaround in the meantime:

> Is it feasible to have a separate pipeline that is only used to update secrets and performs a revision restart?

Imagine we have a template that looks like this:

```
@secure()
param acrPassword string

@secure()
param thirdPartyApiKey string

resource storageAccount = {
  ...
}

resource containerApp = {
  registries: [
    {
      server: 'my-container-registry.azurecr.io'
      username: 'my-container-registry'
      passwordSecretRef: 'acr-password'
    }
  ]
  secrets: [
    {
      name: 'acr-password'
      value: acrPassword
    }
    {
      name: 'storage-account-key'
      value: storageAccount.listKeys().keys[0].value
    }
    {
      name: 'third-party-api-key'
      value: thirdPartyApiKey
    }
  ]
  template: {
    containers: [
      {
        image: 'something-image-from-container-regsitry'
        env: [
          {
            name: 'storageAccountKey'
            secretRef: 'storage-account-key'
          }
          {
            name: 'thirdPartyApi'
            value: 'https://third-party-api.com/'
          }
          {
            name: 'thirdPartyApiKey'
            secretRef: 'third-party-api-key'
          }
        ]
      }
    ]
  }
}
```

There is three types of secrets here:

* `acr-password`: container registry password
* `storage-account-key`: the output of a resource (not necessarily a storage account) in the same template file _that could even change when deploying the template_
* `third-party-api-key`: third party api key which is a template parameter and comes from outside the template

How do you recommend I split this template/pipeline to be able to restart the revision when any of these three changes?

I can potentially have a pipeline that uses `az containerapp secret set` for `third-party-api-key` and then `az containerapp revision restart`, but can't do much about the other two.

Even with `az containerapp secret set`, then= next time I deploy this template that secret gets removed because that doesn't exist in the template file.

**Comment by hamenu** [comment]
Actually, on second thought, I don't think even this feature request fixes all scenarios.

For example, I might have a key vault in my Bicep example above. Even if Azure restarts revisions automatically when container app's secrets changed, _I am_ still responsible to detect a change in secrets saved in key vault, and restart the revisions.

Thanks a lot @vturecek for taking the time and explaining everything clearly. Really appreciate it 🙏

So, the solution is actually simple: restart the revision every time we deploy the infrastructure pipeline. We can optionally check if the pipeline has not created a new revision, then restart to avoid restarting a freshly created revision.

Thanks again for your time 🙏

Closing the issue...
