### ISSUE TITLE
Container App with secret parameter | ERROR: ambiguous option: --secret could match --secrets, --secret-volume-mount

### ISSUE THREAD

**Issue by khushkore** [microsoft/azure-container-apps#746]
I am facing the issue while deploying the new container app using the command `az containerapp create`. This command was running perfectly good April 24, 2023 and it started creating problems on May 10, 2023. 
Error Message: 
`ERROR: ambiguous option: --secret could match --secrets, --secret-volume-mount`

Command: 
`az containerapp create 
--resource-group <rg-name> 
--environment <env-name> 
--name <container-name> 
--image <docker-image> 
--cpu 2.0 --memory 4.0Gi 
--registry-server <docker-registry> 
--registry-username <docker-username> 
--registry-password <docker-password> 
--ingress 'external' 
--env-vars <envs> 
--secret azure-client-id=$AZURE_CLIENT_ID azure-client-secret=$AZURE_CLIENT_SECRET azure-tenant-id=$AZURE_TENANT_ID 
--target-port <port-number> 
--exposed-port <exposed-port-number> 
--max-replicas 3 
--min-replicas 6 
--scale-rule-name <scale-rule-name> 
--scale-rule-type http 
--scale-rule-http-concurrency 1`

Any help would be appreciated. Thank you.

**Comment by smzeng** [comment]
Hi @khushkore. From your command I believe you are trying to define secrets for your container app. You are just missing a letter 's' in your flag. The correct flag for that is --secret**s** (documentation: https://learn.microsoft.com/en-us/cli/azure/containerapp?view=azure-cli-latest#az-containerapp-create). 

The reason this command worked before is because there were not multiple flags that began with --secret. But we recently added the new flag --secret-volume-mount. Therefore, now you have to be exact with the spelling of the flags or else you will run into the above error.

please let me know if this does not solve your issue.

**Comment by khushkore** [comment]
@smzeng Thank you for your reply. It looks good and resolved my issue. Appreciated!
