### ISSUE TITLE
Security concerns when using containers apps for a SAAS offering

### ISSUE THREAD

**Issue by bppn** [microsoft/azure-container-apps#751]
The intention is to launch a saas product where end-users can easily run containers on the fly.  We would like to use containers apps for this.

I am looking for some guidance in order to have a secure offering.

Which kind of issues are present when the containers are provisioned in the same Azure Container Environment?
- When ingress is turned off, can apps use network communication to reach other apps in the same environment
- Can end-users eardrop on other containers?  Like traffic, container image...

What kind of measures can be taken to co-host multiple customers in one enviroment?

Or is it better to provision each customer in a separate container enviroment?

Thanks for the insights!

**Comment by kazeno** [comment]
ACA runs on Kubernetes, so most of the same security considerations apply here. Each Container App is a Kubernetes pod, and each Environment is basically an isolated node running the pods. While ACA does provide basic ingress security options per each App, some of which are still broken (hello IP whitelists on TCP apps!), the basic Kubernetes premise is to facilitate communication between pods, so I would definitely provision a separate Environment for each customer.

**Comment by bppn** [comment]
Having each customer in a separate environment would indeed be the most ideal situation.  However, the problem is that there is a limit to 15 env/subscription/region.  For a saas tool this is a very low limit.  Having to maintain multiple subscriptions/regions would be an administrative burden...

The containers are indeed untrusted, so I am looking into ways to minimize the security impact while still be able to host them in one environment.  Customers who seek more isolation can pay more for a dedicated environment.

When apps have ingress disabled or when customer containers are deployed as a sidecar to a reverse-proxy (controlling communication/auth), what would be other concerns, typical related to running them as pods in one environment.

Would it be possible for low-level hardware access (memory, disk, internal network, ...) by untrusted containers?

I see there is a preview for isolated pods on AKS, using KATA.  Would this also be possible to integrate in ACA?

**Comment by kazeno** [comment]
Containers can't run as priviledged, so their low level access is very limited. However, in terms of functionality, take into account that:
1. Each environment has the same IP address for all its apps
2. Different apps in the same environment can't have ingress on the same port, because of the point above, except for:
3. HTTP apps (which) must all use port 80 and 443 for ingress, and all run behind the same built-in Envoy Proxy which is pretty much not configurable, apart from custom domains and very basic security features.

As for KATA, the ACA team hasn't announced anything AFAIK, which means it's not going to be supported at least for the near future.

**Comment by simonjj** [comment]
You should be able to request quota for more than 15 environments now. Also, we've also just launched dynamic sessions which might fit your needs too.
