### ISSUE TITLE
I'm getting an error when trying to `build image in Azure...` when following quickstart

### ISSUE THREAD

**Issue by rodsantest1** [microsoft/azure-container-apps#767]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
I'm following along quickstart page
https://learn.microsoft.com/en-us/azure/container-apps/deploy-visual-studio-code
Images of error here:  
https://stackoverflow.com/q/76369434/139698

### Steps to reproduce
1. ..I'm in VS Code signed in with my Azure account
2. ..In article, I'm at [Create Registry and Container image](https://learn.microsoft.com/en-us/azure/container-apps/deploy-visual-studio-code#create-the-container-registry-and-docker-image)  

**Expected behavior** [What you expected to happen.]
I expected it to build an image in my Azure

**Actual behavior** [What actually happened.]
Got error on COPY in Dockerfile

**Screenshots**         

### Additional context
Ex. Did this issue occur in the CLI or the Portal?

**Comment by anthonychu** [comment]
@rodsantest1 Sorry you ran into this. Looks like the Docker extension might have changed slightly since the instructions were published. Can you try again and ensure you select "Linux" when prompted? The example Dockerfile builds Linux containers and Azure Container Apps only supports running Linux containers.

<img width="298" alt="image" src="https://github.com/microsoft/azure-container-apps/assets/3982077/7dc7a728-4934-4c33-abf2-e245a92c9e5b">
