### ISSUE TITLE
Namespaces

### ISSUE THREAD

**Issue by Squixx** [microsoft/azure-container-apps#81]
Within a large organisation, we have the need to share SOME, but not all resources between teams. 

Kubernetes allowes us to set namespaces within a cluster, where some services can explicitly communicate between namespaces.

Will namespaces be possible within container apps?

**Comment by ThorstenHans** [comment]
Uh, that's interesting. 

So what's the point of your question @Squixx ? Is your intention running multiple ACA environments? Where each team has it's own ACA environment? Is that because of regulatory compliance or an organizational / resource ownership thing?

Here some of my raw thoughts about the scenario:

- Right now, you have to put everything in the same ACA environment to have downstream services communicating with each outer without using external ingress capabilities. Which would lead to having all your resources in a single ACA environment. 
- From the service point of view, Namspacing in the scope of a single ACA environment would make adding RBAC permissions on the ARM resource more complicated, I guess
- I have not looked at custom vNet integration in depth. However, this could also be an option. Consider having your "shared" environment deployed to your vNet and NSGs or ASGs ensuring upstream ACA environments can call into the shared layer... However, this would required private DNS zone and all the other networking stuff to work with ACA...

**Comment by Squixx** [comment]
Right so an example would be:

We have 2 teams (but the same org)  running their own microservice app. All internally communicating through dapr, within the same vnet.

They have _some_ services that should be shared, and also accessible though 'simple' dapr calls. 

namespaces would allow you to use one ACA environment for N teams,

While still only allowing team A and B to reach app Z

While team C would not be able to reach app Z through DAPR

_or_ have one ACA envrionment for dev/test/acceptance/prod. But apps inside the namespace 'prod' can only reach other apps within the 'prod'  namespace. 


So the main use would be to allow/block certain internal traffic, while still having all vnet / dapr benefits

**Comment by SatyKrish** [comment]
With virtual network integration, each container app environment requires a /23 subnet atleast (512 ips). We would like to have logical isolation for Engg, Dev and DevInt within same container app environment. 

Creating a container app environment per deployment environment is a wastage of IPs, which is usually limited in large organisations.

**Comment by simonjj** [comment]
We've optimized IP usage now. We're not looking to enable namespaces for the foreseeable future. Please reopen if you feel strongly. https://learn.microsoft.com/en-us/azure/container-apps/networking?tabs=workload-profiles-env%2Cazure-cli#subnet
