### ISSUE TITLE
az containerapps exec errors & disconnection

### ISSUE THREAD

**Issue by geremy42** [microsoft/azure-container-apps#849]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [X] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
When querying the console logs of an app using the CLI with the following command :

`az containerapp logs show -n test -g testrg`

I get the following error :
`Failed to ping container app with error 'HTTPSConnectionPool(host='test.wittypebble-f6e327af.francecentral.azurecontainerapps.io', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x05572F70>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))'
Please ensure there is an alive replica.`

(I didn't get same error using Console available through Azure portal.

Despite this error, I'm able to run command to my replica without any issues.  But got disconnected after 30s of inactivity. Is-it normal behavior ?

### Steps to reproduce
1. Deploy an app serving TCP requests with ingress configured on specific port (5557)
2. Issue the `az containerapp exec -n ...' command

**Expected behavior** [What you expected to happen.]

No errors when using exec command

**Actual behavior** [What actually happened.]

Throws an error with the following message :
`Failed to ping container app with error 'HTTPSConnectionPool(host='test.wittypebble-f6e327af.francecentral.azurecontainerapps.io', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x05572F70>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))'
Please ensure there is an alive replica.`

**Comment by xwang971** [comment]
Hi @geremy42 sorry for the inconvenience. Do you mean that the logstream CLI command, it complains that `Failed to ping container app with error 'HTTPSConnectionPool(host='test.wittypebble-f6e327af.francecentral.azurecontainerapps.io', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x05572F70>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))' Please ensure there is an alive replica` ? Can you please check if there is active replica when you run the command? The logstream/exec would only connect to the running container.
If there is indeed running replica at that time, could you please try the whole command `az containerapp logs show -n MyContainerapp -g MyResourceGroup --replica MyReplica --revision MyRevision --container MyContainer`([ACA CLI](https://learn.microsoft.com/en-us/cli/azure/containerapp/logs?view=azure-cli-latest#az-containerapp-logs-show)) to see if this resolve the problem?
Can you also provide the subscription/environmentId of the containerapp you were testing against to email acasupport@microsoft.com?

**Comment by geremy42** [comment]
Yes, there are 2 active replicas. 

You're right, when my exec command is targeting only one replica by specifying `-replica MyReplica --revision MyRevision --container MyContainer`, I don't get any errors.

![image](https://github.com/microsoft/azure-container-apps/assets/39192567/a5a3824b-1d43-451b-b37d-57a23a25bc59)

![image](https://github.com/microsoft/azure-container-apps/assets/39192567/0b479e03-7a09-4b54-9f42-2072c8f55f9b)

I still facing the issue of being disconnected after 30s of inactivity, which is a bit short to me.

**Comment by xwang971** [comment]
Hi @geremy42, the error message is a bug from our side that it tries to ping the containerapp to see if there is active replica at port 443 which is not correct since your app is configured at 5557. The error could be ignored since it would still fetch replica and connect to it. We would fix it for sure.
For the disconnection issue, is that happening at portal as well? Did you try any commands? If yes did they work?

**Comment by simonjj** [comment]
This issue should be resolved now. Please reopen if it persists.
